export const UPDATE_VERSION = 'UPDATE_VERSION'

export const UPDATE_MULTIINFO = 'UPDATE_MULTIINFO'

export const UPDATE_SETTING_N3T5 = 'UPDATE_SETTING_N3T5'

export const UPDATE_SETTING_MAINNET = 'UPDATE_SETTING_MAINNET'

export const UPDATE_SETTING_CURNETID = 'UPDATE_SETTING_CURNETID'

export const UPDATE_SCPARAMS = 'UPDATE_SCPARAMS'
